const API = "";
const state = { timetable: [], members: [] };
const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];
const slots = ["08:30", "09:30", "10:30", "11:30", "12:30", "13:30", "14:30", "15:30", "16:30", "17:30"];
const $ = (selector) => document.querySelector(selector);
if (!document.getElementById("freeRooms")) { const compatibilityRoomOutput = document.createElement("div"); compatibilityRoomOutput.id = "freeRooms"; compatibilityRoomOutput.hidden = true; document.body.append(compatibilityRoomOutput); }
const themeStorageKey = "timetable-theme";
document.documentElement.dataset.theme = localStorage.getItem(themeStorageKey) === "dark" ? "dark" : "light";
const timeValue = (time) => { const match = String(time).match(/(\d{1,2}):(\d{2})/); return match ? Number(match[1]) * 60 + Number(match[2]) : Number.MAX_SAFE_INTEGER; };
const slotKey = (day, time) => `${day}-${timeValue(time)}`;
function setMessage(text, error = false) { $("#message").textContent = text; $("#message").style.color = error ? "#a44b4b" : ""; }
function optionMarkup(values, placeholder) { return `<option value="">${placeholder}</option>${values.map((value) => `<option value="${value}">${value}</option>`).join("")}`; }
async function json(url, options = {}) { const response = await fetch(url, { credentials: "include", ...options }); if (!response.ok) throw new Error(`SR University returned ${response.status}`); return response.json(); }
async function getToken() { const html = await (await fetch(`${API}/batchReport`, { credentials: "include", cache: "no-store" })).text(); return html.match(/name=["']csrf-token["'][^>]*content=["']([^"']+)/i)?.[1] || html.match(/name=["']_token["'][^>]*value=["']([^"']+)/i)?.[1]; }
async function loadTimetable(batch, year) { const token = await getToken(); if (!token) throw new Error("SR University token was not found"); const data = await json(`${API}/searchBatchReport2Public`, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded", "X-CSRF-TOKEN": token, "X-Requested-With": "XMLHttpRequest" }, body: new URLSearchParams({ _token: token, batch, year }) }); const records = []; Object.entries(data.data || {}).forEach(([day, times]) => Object.entries(times || {}).forEach(([time, entries]) => entries.forEach((entry) => records.push({ day, time, subject: entry.subject || "Class", faculty: entry.facultyName || entry.faculty_name || entry.faculty || "-", room: entry.room_name || entry.room_no || entry.room || "-", type: /lab|practical/i.test(`${entry.subject} ${entry.ltp || ""}`) ? "Lab" : "Class" })))); return records.sort((a, b) => days.indexOf(a.day) - days.indexOf(b.day) || timeValue(a.time) - timeValue(b.time)); }
function renderSchedule(query = "") { const normalized = query.toLowerCase().trim(); const selectedDay = $("#dayFilter").value; const rows = state.timetable.filter((entry) => (selectedDay === "All" || entry.day === selectedDay) && `${entry.subject} ${entry.faculty}`.toLowerCase().includes(normalized)); $("#scheduleBody").innerHTML = rows.map((entry) => `<tr><td>${entry.day}</td><td>${entry.time}</td><td class="subject">${entry.subject}</td><td>${entry.faculty}</td><td><span class="room-tag">${entry.room}</span></td><td><span class="type-tag">${entry.type}</span></td></tr>`).join(""); $("#scheduleEmpty").style.display = rows.length ? "none" : "block"; $("#scheduleSummary").textContent = `${rows.length} timetable entries loaded${selectedDay === "All" ? "" : ` for ${selectedDay}`}`; }
function status(entry) { return entry ? `<span class="availability busy">${entry.type}</span>` : `<span class="availability free">Free</span>`; }
function renderRooms() { const selected = $("#freeSlot").value; const allRooms = [...new Set(state.members.flatMap((member) => member.entries.map((entry) => String(entry.room || "").trim()).filter((room) => room && room !== "-")))]; const used = new Set(state.members.flatMap((member) => member.entries.filter((entry) => slotKey(entry.day, entry.time) === selected).map((entry) => String(entry.room || "").trim()))); const available = allRooms.filter((room) => !used.has(room)); $("#freeRooms").innerHTML = available.length ? available.map((room) => `<span class="room-tag">${room}</span>`).join(" ") : "No known room is free at this time."; }
function renderComparison() { const hasComparison = state.members.length >= 2; const members = hasComparison ? state.members : [{ name: "Member 1", entries: state.timetable }, { name: "Member 2", entries: [] }]; const maps = members.map((member) => new Map(member.entries.map((entry) => [slotKey(entry.day, entry.time), entry]))); const all = days.flatMap((day) => slots.map((time) => ({ day, time }))); const free = hasComparison ? all.filter((slot) => maps.every((map) => !map.has(slotKey(slot.day, slot.time)))) : []; $("#compareHead").innerHTML = `<tr><th>Day</th><th>Time</th>${members.map((member) => `<th>${member.name}</th>`).join("")}<th>Shared</th></tr>`; $("#compareBody").innerHTML = all.map((slot) => { const key = slotKey(slot.day, slot.time); const statuses = maps.map((map) => status(map.get(key))); const shared = hasComparison && maps.every((map) => !map.has(key)); return `<tr class="${shared ? "shared-free" : ""}"><td>${slot.day}</td><td>${slot.time}</td>${statuses.map((value) => `<td>${value}</td>`).join("")}<td>${shared ? `<span class="availability free">Free</span>` : "-"}</td></tr>`; }).join(""); $("#compareSummary").textContent = hasComparison ? `${free.length} shared free periods across ${members.length} selected batches` : "Select at least two batches."; $("#freeSlot").innerHTML = free.length ? free.map((slot) => `<option value="${slotKey(slot.day, slot.time)}">${slot.day}, ${slot.time}</option>`).join("") : '<option value="">No shared free time</option>'; $("#freeRooms").textContent = hasComparison ? "No known room is free at this time." : "Select at least two batches to search rooms."; if (hasComparison) renderRooms(); }
async function populate(select, url, key, placeholder) { const payload = await json(url); const values = [...new Set((payload.yearList || payload.batchList || []).map((item) => item[key]).filter(Boolean))]; select.innerHTML = optionMarkup(values, placeholder); }
function renderMemberPicker() { const select = $("#members"); let picker = $("#memberPicker"); if (!picker) { picker = document.createElement("div"); picker.id = "memberPicker"; picker.className = "member-picker"; select.insertAdjacentElement("afterend", picker); select.hidden = true; } picker.innerHTML = [...select.options].filter((option) => option.value).map((option) => `<label><input type="checkbox" value="${option.value}"><span>${option.textContent}</span></label>`).join("") || "<span class=\"picker-empty\">Select a degree and year first</span>"; picker.querySelectorAll("input").forEach((input) => input.addEventListener("change", () => { const option = [...select.options].find((item) => item.value === input.value); if (option) option.selected = input.checked; })); }
const degreeValues = ["BTECH-CSE", "BTECH", "BTECH-CE", "BTECH-ECE", "BTECH-EEE", "BTECH-ME", "BCA-CSAI", "MCA-CSE", "MBA-BM", "B.Com-BM", "BBA-BM", "MTECH-CSE"];
function setTheme(theme) { document.documentElement.dataset.theme = theme; const dark = theme === "dark"; $("#themeToggle").innerHTML = `<span aria-hidden="true">${dark ? "☀" : "☾"}</span><span class="theme-label">${dark ? "Light" : "Dark"}</span>`; $("#themeToggle").ariaLabel = `Switch to ${dark ? "light" : "dark"} theme`; $("#themeToggle").title = `Switch to ${dark ? "light" : "dark"} theme`; localStorage.setItem(themeStorageKey, theme); }
$("#themeToggle").addEventListener("click", () => setTheme(document.documentElement.dataset.theme === "dark" ? "light" : "dark")); $("#compareDegree").innerHTML = optionMarkup(degreeValues, "Select Degree");
$("#compareDegree").addEventListener("change", async (event) => { $("#compareYear").disabled = true; $("#members").innerHTML = "<option>Select a year first</option>"; try { await populate($("#compareYear"), `${API}/get-yearbpublic?degree=${encodeURIComponent(event.target.value)}`, "year", "Select Year"); $("#compareYear").disabled = false; } catch (error) { $("#compareSummary").textContent = "Could not load comparison years."; } });
$("#compareYear").addEventListener("change", async (event) => { try { await populate($("#members"), `${API}/get-batchbpublic?year=${encodeURIComponent(event.target.value)}&degree=${encodeURIComponent($("#compareDegree").value)}`, "batch", "Select batches"); renderMemberPicker(); } catch (error) { $("#compareSummary").textContent = "Could not load comparison batches."; } });
$("#degree").addEventListener("change", async (event) => { $("#year").disabled = true; $("#batch").disabled = true; $("#year").innerHTML = '<option value="">Loading years...</option>'; if (!event.target.value) { $("#year").innerHTML = '<option value="">Select Year</option>'; setMessage("Select a degree first."); return; } try { await populate($("#year"), `${API}/get-yearbpublic?degree=${encodeURIComponent(event.target.value)}`, "year", "Select Year"); $("#year").disabled = false; setMessage("Choose a year to load batches."); } catch (error) { $("#year").innerHTML = '<option value="">Years unavailable</option>'; setMessage("Could not load years from SR University. Check that the local server is running.", true); } });
$("#year").addEventListener("change", async (event) => { try { await populate($("#batch"), `${API}/get-batchbpublic?year=${encodeURIComponent(event.target.value)}&degree=${encodeURIComponent($("#degree").value)}`, "batch", "Select Batch"); $("#batch").disabled = false; setMessage("Select a batch, or choose two or more below for comparison."); } catch (error) { setMessage("Could not load batches from SR University.", true); } });
$("#searchForm").addEventListener("submit", async (event) => { event.preventDefault(); try { setMessage("Loading timetable..."); state.timetable = await loadTimetable($("#batch").value, $("#year").value); renderSchedule($("#rowSearch").value); state.members = [{ name: $("#batch").value, entries: state.timetable }]; renderComparison(); setMessage(`Live timetable loaded for ${$("#batch").value}.`); } catch (error) { setMessage("Live timetable could not be loaded. Check the source connection.", true); } });
$("#compareButton").addEventListener("click", async () => { const selected = [...$("#members").selectedOptions].map((option) => option.value).filter(Boolean); if (selected.length < 2) { $("#compareSummary").textContent = "Select at least two batches."; return; } const year = $("#compareYear").value; if (!year) { $("#compareSummary").textContent = "Select a comparison degree and year first."; return; } try { setMessage("Loading selected batch timetables..."); state.members = await Promise.all(selected.map(async (batch) => ({ name: batch, entries: await loadTimetable(batch, year) }))); renderComparison(); setMessage(`${selected.length} batch timetables compared.`); } catch (error) { $("#compareSummary").textContent = "One or more selected batch timetables could not be loaded."; } });
$("#rowSearch").addEventListener("input", (event) => renderSchedule(event.target.value)); $("#dayFilter").addEventListener("change", () => renderSchedule($("#rowSearch").value)); $("#freeSlot").addEventListener("change", renderRooms); $("#refreshRooms").addEventListener("click", renderRooms); $("#liveRooms")?.addEventListener("click", () => { const now = new Date(); const day = days[now.getDay() - 1]; if (!day) { $("#freeRooms").textContent = "Live room search is available Monday to Friday."; return; } renderRooms(); });
function init() { $("#degree").innerHTML = optionMarkup(degreeValues, "Select Degree"); setTheme(localStorage.getItem(themeStorageKey) === "dark" ? "dark" : "light"); setMessage("Select a degree to load the complete SR University dataset."); renderComparison(); }
init();

let classroomRooms = [];
let classroomOccupancy = {};
const parseClassroom = (code) => { const parts = code.split("-"); const blockMatch = code.match(/BL(\d+)/i); const block = blockMatch ? `Block ${blockMatch[1]}` : "Unknown block"; const floor = parts[2] === "GF" ? "Ground Floor" : parts[2] === "FF" ? "First Floor" : parts[2] === "SF" ? "Second Floor" : "Third Floor"; return { code, block, number: parts[0], floor }; };
const classroomMinutes = (time) => { const [hour, minute] = time.split(":").map(Number); return hour * 60 + minute; };
const classroomDay = () => days[(new Date().getDay() + 6) % 7] || "Monday";
const classroomTime = () => { const now = new Date(); const current = now.getHours() * 60 + now.getMinutes(); return slots.reduce((best, slot) => Math.abs(classroomMinutes(slot) - current) < Math.abs(classroomMinutes(best) - current) ? slot : best, slots[0]); };
function renderClassrooms() { const block = $("#roomBlock").value; const day = $("#roomDay").value === "Today" ? classroomDay() : $("#roomDay").value; const time = $("#roomTime").value === "now" ? classroomTime() : $("#roomTime").value; const pool = block === "All blocks" ? classroomRooms : classroomRooms.filter((room) => room.block === block); const busy = pool.filter((room) => classroomOccupancy[room.code]?.[day]?.[time]?.busy); const free = pool.filter((room) => !classroomOccupancy[room.code]?.[day]?.[time]?.busy); $("#roomFreeCount").textContent = free.length; $("#roomBusyCount").textContent = busy.length; $("#roomTotalCount").textContent = pool.length; $("#nativeRooms").innerHTML = free.length ? free.map((room) => `<span class="room-tag">${room.number}<small>Free · ${room.block}</small></span>`).join("") : "No free rooms found for this selection."; }
["roomBlock", "roomDay", "roomTime"].forEach((id) => $("#" + id).addEventListener("change", renderClassrooms)); $("#findRooms").addEventListener("click", renderClassrooms); $("#nativeRooms").textContent = "Loading classroom data..."; fetch("/classroom-data").then((response) => { if (!response.ok) throw new Error("Classroom data unavailable"); return response.json(); }).then((data) => { classroomOccupancy = data; classroomRooms = Object.keys(data).map(parseClassroom).sort((a, b) => a.number.localeCompare(b.number, undefined, { numeric: true })); renderClassrooms(); }).catch(() => { $("#nativeRooms").textContent = "Classroom data could not be loaded. Check the backend connection."; });
